"""Shared default operator definitions for Prolog parsing and semantics."""

from __future__ import annotations

DEFAULT_OPERATORS: list[tuple[int, str, str]] = [
    (1200, "xfx", ":-"),
    (1200, "fx", ":-"),
    (1200, "fx", "?-"),
    (1200, "xfx", "-->"),
    (1100, "xfy", ";"),
    (1050, "xfy", "->"),
    (1000, "xfy", ","),
    (900, "fy", "\\+"),
    (700, "xfx", "=.."),
    (700, "xfx", "is"),
    (700, "xfx", "="),
    (700, "xfx", "\\="),
    (700, "xfx", "=:="),
    (700, "xfx", "=\\="),
    (700, "xfx", "<"),
    (700, "xfx", ">"),
    (700, "xfx", "=<"),
    (700, "xfx", ">="),
    (700, "xfx", "=="),
    (700, "xfx", "\\=="),
    (700, "xfx", "@<"),
    (700, "xfx", "@=<"),
    (700, "xfx", "@>"),
    (700, "xfx", "@>="),
    (600, "xfy", ":"),
    (500, "yfx", "+"),
    (500, "yfx", "-"),
    (500, "yfx", "/\\"),
    (500, "yfx", "\\/"),
    (400, "yfx", "*"),
    (400, "yfx", "/"),
    (400, "yfx", "//"),
    (400, "yfx", "mod"),
    (400, "yfx", "div"),
    (400, "yfx", "rem"),
    (400, "yfx", "<<"),
    (400, "yfx", ">>"),
    (200, "xfy", "**"),
    (200, "xfy", "^"),
    (200, "fy", "+"),
    (200, "fy", "-"),
    # CLP(Z)-style comparison operators needed by bundled libraries
    (700, "xfx", "#>"),
    (700, "xfx", "#<"),
    (700, "xfx", "#>="),
    (700, "xfx", "#=<"),
    (700, "xfx", "#="),
    (700, "xfx", "#\\="),
    (700, "xfx", "in"),
    (700, "xfx", "ins"),
    (450, "xfx", ".."),
    # Scryer-specific operator (recognized but directive is ignored)
    (700, "fx", "non_counted_backtracking"),
    # Attribute declaration for attributed variables
    (1150, "fx", "attribute"),
    # Rational division (Scryer-specific)
    (400, "yfx", "rdiv"),
]

__all__ = ["DEFAULT_OPERATORS"]
