#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.12"
# ///
import sys

from autocoder_utils.issue_workflow import IssueWorkflowConfig, run_issue_workflow


def main(argv: list[str]) -> None:
    config = IssueWorkflowConfig(
        tool_cmd=["kilocode", "--auto"],
        branch_prefix="fix-kilocode",
        default_commit_message="Update from kilocode",
    )
    run_issue_workflow(argv, config)


if __name__ == "__main__":
    main(sys.argv)
